apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-deployment
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate        
  selector:
    matchLabels:
      {{ .Values.selector.key }}: {{ .Values.selector.value }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        checksum/secret: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}            
      labels:
        {{ .Values.selector.key }}: {{ .Values.selector.value }}
    spec:
      imagePullSecrets:
        {{- toYaml  .Values.imagePullSecrets | nindent 8 }}      
      containers:
      - name: {{ .Values.image.name }}
        image: {{ .Values.image.repository }}
        imagePullPolicy: {{ .Values.image.pullpolicy }}
        envFrom:
        - configMapRef:
             name: {{ .Chart.Name }}-configmap
        - secretRef:
             name: {{ .Chart.Name }}-secret        
        ports:
        - containerPort: {{ .Values.service.targetPort }}
        resources:
          {{- toYaml .Values.resources | nindent 12}}
